-- ============================================================
-- Hotel Service Request Management System
-- PostgreSQL Schema (Supabase Compatible)
-- ============================================================


-- ============================================================
-- 1. DEPARTMENTS
-- Created first because staff references it via department_id
-- and tasks also reference it via department_id.
-- Note: departments.default_staff_id FK is added AFTER staff
-- is created to avoid circular dependency.
-- ============================================================

CREATE TABLE IF NOT EXISTS departments (
    id                SERIAL PRIMARY KEY,
    name              TEXT NOT NULL UNIQUE,
    description       TEXT,
    default_staff_id  INTEGER,          -- FK added below after staff table
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE departments IS 'Hotel service departments (e.g. housekeeping, laundry).';
COMMENT ON COLUMN departments.default_staff_id IS
    'The staff member auto-assigned when a new task is created for this department.';


-- ============================================================
-- 2. STAFF
-- References departments for the employee department assignment.
-- ============================================================

CREATE TABLE IF NOT EXISTS staff (
    id              SERIAL PRIMARY KEY,
    name            TEXT NOT NULL,
    phone_number    TEXT NOT NULL,
    department_id   INTEGER NOT NULL REFERENCES departments (id) ON DELETE RESTRICT,
    role            TEXT NOT NULL DEFAULT 'staff'
                        CHECK (role IN ('staff', 'supervisor', 'manager')),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE staff IS 'Hotel employees responsible for completing service tasks.';
COMMENT ON COLUMN staff.is_active IS
    'Soft-delete flag. Set to FALSE when staff leave instead of deleting, '
    'so historical task assignments remain valid.';
COMMENT ON COLUMN staff.role IS 'staff | supervisor | manager';


-- ============================================================
-- 3. ADD FK: departments.default_staff_id → staff.id
-- Added after staff table exists to resolve circular dependency.
-- DEFERRABLE INITIALLY DEFERRED allows seeding both tables
-- in a single transaction without ordering issues.
-- ============================================================

ALTER TABLE departments
    ADD CONSTRAINT fk_departments_default_staff
    FOREIGN KEY (default_staff_id)
    REFERENCES staff (id)
    ON DELETE SET NULL
    DEFERRABLE INITIALLY DEFERRED;


-- ============================================================
-- 4. ROOMS
-- Standalone reference table for hotel rooms.
-- ============================================================

CREATE TABLE IF NOT EXISTS rooms (
    id           SERIAL PRIMARY KEY,
    room_number  TEXT NOT NULL UNIQUE,
    floor        INTEGER,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE rooms IS 'Hotel rooms that guests occupy and tasks are associated with.';


-- ============================================================
-- 5. TASKS
-- Core operational table. FK references rooms, departments,
-- and staff. task_code (T<id>) is generated by a trigger.
-- ============================================================

CREATE TABLE IF NOT EXISTS tasks (
    id                SERIAL PRIMARY KEY,
    task_code         TEXT UNIQUE,                        -- Auto-generated: T<id>
    room_id           INTEGER NOT NULL REFERENCES rooms (id) ON DELETE RESTRICT,
    department_id     INTEGER NOT NULL REFERENCES departments (id) ON DELETE RESTRICT,
    assigned_staff_id INTEGER REFERENCES staff (id) ON DELETE SET NULL,
    task_type         TEXT NOT NULL,
    priority          TEXT NOT NULL DEFAULT 'normal'
                          CHECK (priority IN ('normal', 'urgent')),
    notes             TEXT,
    status            TEXT NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'completed')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at      TIMESTAMPTZ
);

COMMENT ON TABLE tasks IS 'Guest service requests — the core operational record.';
COMMENT ON COLUMN tasks.task_code IS
    'Human-readable code in the format T<id> (e.g. T142). '
    'Used for SMS-based completion replies in future phases.';
COMMENT ON COLUMN tasks.assigned_staff_id IS
    'Auto-populated from departments.default_staff_id at creation time. '
    'Can be overridden manually.';
COMMENT ON COLUMN tasks.priority IS 'normal | urgent';
COMMENT ON COLUMN tasks.status IS 'pending | completed';
COMMENT ON COLUMN tasks.completed_at IS
    'Populated when status transitions to completed.';


-- ============================================================
-- 6. TRIGGER: Auto-generate task_code after INSERT
-- Runs after the row is inserted so the SERIAL id is available.
-- Sets task_code = 'T' || id (e.g. T142).
-- ============================================================

CREATE OR REPLACE FUNCTION generate_task_code()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE tasks
       SET task_code = 'T' || NEW.id
     WHERE id = NEW.id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_generate_task_code
AFTER INSERT ON tasks
FOR EACH ROW
EXECUTE FUNCTION generate_task_code();


-- ============================================================
-- 7. INDEXES
-- Improve query performance for common dashboard queries.
-- ============================================================

-- Filter / sort tasks by creation time (dashboard default sort)
CREATE INDEX IF NOT EXISTS idx_tasks_created_at
    ON tasks (created_at DESC);

-- Filter tasks by status (pending vs completed tabs/views)
CREATE INDEX IF NOT EXISTS idx_tasks_status
    ON tasks (status);

-- Filter tasks by assigned staff (staff workload view)
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_staff_id
    ON tasks (assigned_staff_id);

-- Filter tasks by department (department-level reporting)
CREATE INDEX IF NOT EXISTS idx_tasks_department_id
    ON tasks (department_id);

-- Lookup task by code (future SMS reply matching)
CREATE INDEX IF NOT EXISTS idx_tasks_task_code
    ON tasks (task_code);

-- Filter staff by active status (exclude inactive in dropdowns)
CREATE INDEX IF NOT EXISTS idx_staff_is_active
    ON staff (is_active);


-- ============================================================
-- END OF SCHEMA
-- ============================================================
